repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: end-of-file-fixer
        stages: [commit]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: local
    hooks:
     - 	id: pytest
       	name: pytest
       	entry: make test
       	language: system
       	always_run: true
       	pass_filenames: false
       	types: [python]
        stages: [push]
